import type {
  AccountAnalyticsResponse,
  DashboardResponse,
  PromptAuditListResponse,
  PromptAuditRecordSummary,
  PromptAuditSessionResponse,
  SettingsOptionsResponse,
} from '@shared/contracts'

export function dashboardFixture(): DashboardResponse {
  const timestamp = '2026-09-06T06:30:00.000Z'
  const resetAt = 1789106400
  const accounts = ['主力账号', '备用账号'].map((label, index) => ({
    key: `account-${index + 1}`,
    label,
    email: `ops-${index + 1}@example.com`,
    accountId: index + 1,
    reset: {
      observation: { resetAt, usedPercent: 75 + index * 6, fetchedAt: 1788676200, observedAt: timestamp },
      cycles: [
        {
          resetAt,
          startAt: resetAt - 604800,
          status: 'current' as const,
          observedAt: timestamp,
          usageUsd: 1548 + index * 360,
          usedPercent: 75 + index * 6,
          estimatedCycleCapacityUsd: 2075 + index * 280,
          reserveUsd: 207 + index * 28,
          allocatableCapacityUsd: 1868 + index * 252,
        },
      ],
    },
    capacity: {
      observedAt: timestamp,
      resetAt,
      usedPercent: 75 + index * 6,
      localStandardCostUsd: 1548 + index * 360,
      estimatedCycleCapacityUsd: 2075.85 + index * 279,
      reserveUsd: 207.59 + index * 27.9,
      allocatableCapacityUsd: 1868.26 + index * 251.1,
      perShareCapacityUsd: 622.75 + index * 83.7,
      shareCount: 3,
      activeSubscriptions: 3,
      status: 'updated' as const,
      message: '容量已同步',
      groups: [
        {
          groupId: 12 + index,
          name: index ? '团队开发分组' : '核心开发分组',
          currentLimitUsd: 600,
          targetLimitUsd: 622.75 + index * 83.7,
          rateMultiplier: 1,
          updated: true,
          status: 'updated' as const,
        },
      ],
    },
  }))
  return {
    generatedAt: timestamp,
    service: { health: 'healthy', version: '3.0.0', startedAt: '2026-09-01T02:00:00Z' },
    accounts,
    infrastructure: accounts.map((account, index) => ({
      accountKey: account.key,
      email: account.email,
      accountId: account.accountId,
      proxy: {
        id: index + 11,
        name: index ? '加拿大 · 家宽出口' : '美国 · 住宅出口',
        status: 'active',
        protocol: 'socks5h',
        endpoint: `192.0.2.${index + 10}:5813`,
      },
    })),
    config: {
      version: 11,
      fixedGroupIds: [1, 2],
      accounts: accounts.map((account, index) => ({
        key: account.key,
        email: account.email,
        label: account.label,
        shareCount: 3,
        reserveMode: 'percent',
        reserveValue: 10,
        targetGroupIds: [12 + index],
        enabled: true,
      })),
      resetSync: {
        intervalSeconds: 180,
        requestTimeoutSeconds: 15,
        resetAtToleranceSeconds: 3600,
        usageDropTolerancePercent: 1,
      },
      capacitySync: { intervalSeconds: 600, minimumUsedPercent: 5, minimumChangeUsd: 1 },
      promptAudit: { maxRequestBodyMiB: 10, normalRetentionDays: 7, riskRetentionDays: 30 },
      userConcurrencySchedule: {
        enabled: true,
        timezone: 'Asia/Shanghai',
        peakWindows: [{ start: '09:00', end: '18:00' }],
        peakConcurrency: 3,
        idleConcurrency: 8,
        peakRpm: 30,
        idleRpm: 120,
        exemptUserIds: [],
      },
    },
    jobs: [
      {
        kind: 'reset',
        health: 'healthy',
        running: false,
        failures: 0,
        message: '周期检查完成',
        lastCompletedAt: timestamp,
        nextRunAt: '2026-09-06T06:33:00Z',
      },
      {
        kind: 'capacity',
        health: 'healthy',
        running: false,
        failures: 0,
        message: '容量同步完成',
        lastCompletedAt: timestamp,
        nextRunAt: '2026-09-06T06:40:00Z',
      },
    ],
    events: [
      {
        id: 'event-1',
        createdAt: timestamp,
        severity: 'success',
        category: 'capacity',
        summary: '主力账号容量已同步，预留 10% 后更新分组周限。',
        accountKey: 'account-1',
        details: { estimatedCapacityUsd: 2075.85, reservePercent: 10, shareCount: 3 },
      },
      {
        id: 'event-2',
        createdAt: '2026-09-06T06:27:00Z',
        severity: 'success',
        category: 'reset',
        summary: '已完成 2 个账号的上游周期检查，当前窗口未变化。',
      },
      {
        id: 'event-3',
        createdAt: '2026-09-06T06:20:00Z',
        severity: 'info',
        category: 'configuration',
        summary: '管理员更新了容量分配策略。',
      },
      {
        id: 'event-4',
        createdAt: '2026-09-06T05:40:00Z',
        severity: 'warning',
        category: 'prompt_audit',
        summary: '发现一条需要进一步复核的用户输入。',
      },
    ],
  }
}
export const promptFixture: PromptAuditRecordSummary = {
  id: 'prompt-1',
  requestId: 'request-example',
  userId: 12,
  userEmail: 'developer@example.com',
  apiKeyId: 1,
  apiKeyName: '开发环境',
  groupId: 12,
  groupName: '核心开发分组',
  model: 'gpt-5.4',
  preview: '请检查这次重构中所有数据状态、交互反馈与移动端布局。',
  promptHash: 'example-sha256-for-local-preview',
  charCount: 31,
  redacted: false,
  truncated: false,
  riskStatus: 'clear',
  riskCategory: '',
  riskScore: 0.01,
  moderationAction: '',
  matchedKeyword: '',
  autoBanned: false,
  fullContentAvailable: true,
  reviewRequired: true,
  captureKind: 'user',
  sessionFingerprint: 'example-session-01',
  sessionSource: 'header_session',
  mediaCount: 0,
  occurrenceCount: 1,
  userStatus: 'active',
  capturedAt: '2026-09-06T06:25:00Z',
  expiresAt: '2026-09-13T06:25:00Z',
}
export const promptsFixture: PromptAuditListResponse = {
  generatedAt: '2026-09-06T06:30:00Z',
  range: 'day',
  page: 1,
  pageSize: 30,
  total: 3,
  totals: { records: 1632, reviewed: 864, notRequired: 768, pending: 3, clear: 852, flagged: 8, error: 1, users: 24 },
  timeline: Array.from({ length: 12 }, (_, index) => ({
    bucket: new Date(Date.UTC(2026, 8, 5, 8 + index * 2)).toISOString(),
    clear: [20, 30, 28, 55, 38, 72, 62, 99, 80, 61, 44, 66][index]!,
    pending: index % 3,
    flagged: index === 7 ? 5 : 1,
    error: 0,
    notRequired: [15, 24, 19, 28, 40, 51, 46, 72, 59, 38, 32, 50][index]!,
  })),
  items: [
    promptFixture,
    {
      ...promptFixture,
      id: 'prompt-2',
      riskStatus: 'flagged',
      riskCategory: '需要复核',
      riskScore: 0.87,
      userId: 13,
      userEmail: 'review@example.com',
      preview: '这条输入被标记为需要人工复核，请查看完整记录。',
      autoBanned: true,
      userStatus: 'disabled',
    },
    {
      ...promptFixture,
      id: 'prompt-3',
      riskStatus: 'not_required',
      reviewRequired: false,
      captureKind: 'function_call_output',
      preview: '构建任务已完成，返回执行结果与测试状态。',
    },
  ],
}
export const sessionFixture: PromptAuditSessionResponse = {
  fingerprint: 'example-session-01',
  startedAt: '2026-09-06T06:20:00Z',
  endedAt: '2026-09-06T06:25:00Z',
  durationMs: 300000,
  totals: { records: 3, reviewed: 2, notRequired: 1, pending: 0, flagged: 1, errors: 0 },
  models: [{ model: 'gpt-5.4', records: 3 }],
  items: promptsFixture.items,
}
export const analyticsFixture: AccountAnalyticsResponse = {
  usersWithUsage: 0,
  accountKey: 'account-1',
  accountId: 1,
  range: 'week',
  startAt: '2026-08-31T00:00:00Z',
  endAt: '2026-09-07T00:00:00Z',
  requests: 2840,
  inputTokens: 824000,
  outputTokens: 44000,
  cacheReadTokens: 640000,
  cacheCreationTokens: 0,
  totalTokens: 1508000,
  costUsd: 128.5,
  cacheHitRate: 43,
  averageTps: 60,
  averageFirstTokenMs: 750,
  averageDurationMs: 14200,
  requestTypes: { websocket: 1000, stream: 1840, sync: 0, live: 0, other: 0 },
  users: [],
}
export const settingsFixture: SettingsOptionsResponse = {
  accounts: dashboardFixture().accounts.map((account) => ({
    id: account.accountId!,
    email: account.email,
    name: account.label,
    status: 'active' as const,
  })),
  groups: [
    { id: 1, name: '固定分组', weeklyLimitUsd: 100 },
    { id: 12, name: '核心开发分组', weeklyLimitUsd: 622.75 },
    { id: 13, name: '团队开发分组', weeklyLimitUsd: 706.45 },
  ],
  users: [
    { id: 12, email: 'developer@example.com', username: 'Developer', concurrency: 3, rpmLimit: 30, status: 'active' },
  ],
}
